[package]
name = "amp"
version = "0.1.0"
authors = ["davemollen <davemollen@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lv2 = "0.5.1"

[lib]
crate-type = ["cdylib"]